version: '3.9'

services:
  # --- Backend (Laravel + PHP-FPM) ---
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - redis

  # --- Frontend (Vue) ---
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "build"]

  # --- Database ---
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- Redis ---
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6380"

  # --- Nginx ---
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
