services:
  # Laravel + Vue (PHP-FPM + Node build stage внутри Dockerfile)
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
      - vendor_data:/var/www/html/vendor
      - build_data:/var/www/html/public/build
      - ./vite.config.js:/var/www/html/vite.config.js:cached
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  # Redis
  redis:
    image: redis:8.2.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  # Nginx
  nginx:
    image: nginx:1.29.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
      - build_data:/var/www/html/public/build:ro
    depends_on:
      - backend
    networks:
      - laravel


volumes:
  postgres_data:
  storage_data:
  cache_data:
  vendor_data:
  build_data:

networks:
  laravel:
    driver: bridge
