version: "3.9"

services:
  # Laravel backend
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  # Vue frontend
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    container_name: frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - laravel

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6380"
    networks:
      - laravel

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge
