version: '3.9'

services:
  # Laravel backend
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
      - redis

  # Vue frontend (уже внутри nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - laravel

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6380"

volumes:
  postgres_data:
