services:
  # Laravel backend
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
      - vendor_data:/var/www/html/vendor
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  # Vue frontend
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - laravel
    depends_on:
      - backend

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/build:/usr/share/nginx/html
      - ./:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - laravel

volumes:
  postgres_data:
  storage_data:
  cache_data:
  vendor_data:

networks:
  laravel:
    driver: bridge
